import { User, Project, RepoCa, Badge, Mission, SeasonPass } from "@/types";

export const currentUser: User = {
  id: "u1",
  name: "菊池",
  teamId: "t1",
  level: 20,
  xp: 160,
  xpToNext: 300,
  currency: 1200,
  avatar: "fox",
  isExternal: false,
};

export const projects: Project[] = [
  { id: "p1", name: "ITS-xLP",                        teamId: "t1", color: "#bbf7d0", textColor: "#065f46", icon: "🔧" },
  { id: "p2", name: "コーポレートサイトリニューアル", teamId: "t1", color: "#e9d5ff", textColor: "#581c87", icon: "🏢" },
  { id: "p3", name: "モバイルアプリ開発",             teamId: "t2", color: "#bfdbfe", textColor: "#1e3a8a", icon: "📱" },
  { id: "p4", name: "データ基盤構築",                 teamId: "t1", color: "#fde68a", textColor: "#78350f", icon: "🗄️" },
];

export const repoCas: RepoCa[] = [
  // ITS-xLP (p1)
  {
    id: "rc1",
    projectId: "p1",
    taskType: "開発",
    label: "新規作成",
    implScope: "フロント",
    content: "Contactページ作成",
    isFavorite: false,
    isCompleted: true,
    duration: 60,
    xp: 50,
    createdAt: "2026-01-25T17:20",
  },
  {
    id: "rc2",
    projectId: "p1",
    taskType: "デイリースクラム",
    label: "その他",
    implScope: "その他",
    content: "デイリースクラム",
    isFavorite: false,
    isCompleted: false,
    duration: 15,
    xp: 10,
    createdAt: "2026-01-25T17:20",
  },
  {
    id: "rc3",
    projectId: "p1",
    taskType: "MTG",
    label: "その他",
    implScope: "その他",
    content: "リファインメント",
    isFavorite: false,
    isCompleted: false,
    duration: 60,
    xp: 15,
    createdAt: "2026-01-25T17:20",
  },
  // コーポレートサイトリニューアル (p2)
  {
    id: "rc4",
    projectId: "p2",
    taskType: "開発",
    label: "新規作成",
    implScope: "フロント",
    content: "会社概要作成",
    isFavorite: false,
    isCompleted: false,
    duration: 300,
    xp: 50,
    createdAt: "2026-01-25T17:20",
  },
  // その他 (p3)
  {
    id: "rc5",
    projectId: "p3",
    taskType: "MTG",
    label: "その他",
    implScope: "その他",
    content: "サブリーダー1on1",
    isFavorite: false,
    isCompleted: false,
    duration: 30,
    xp: 20,
    createdAt: "2026-01-25T17:20",
  },
  // 未完了RepoCa（右サイドバー用）
  {
    id: "rc6",
    projectId: "p1",
    taskType: "開発",
    label: "新規作成",
    implScope: "フロント",
    content: "ヘッダーの作成",
    isFavorite: false,
    isCompleted: false,
    duration: 0,
    xp: 50,
    createdAt: "2026-01-24T10:00",
  },
  {
    id: "rc7",
    projectId: "p1",
    taskType: "開発",
    label: "新規作成",
    implScope: "インフラ",
    content: "stg用インフラの構築",
    isFavorite: false,
    isCompleted: false,
    duration: 0,
    xp: 60,
    createdAt: "2026-01-24T11:00",
  },
  // お気に入りRepoCa
  {
    id: "rc8",
    projectId: "p1",
    taskType: "MTG",
    label: "その他",
    implScope: "その他",
    content: "エンジニア定例",
    isFavorite: true,
    isCompleted: false,
    duration: 60,
    xp: 20,
    createdAt: "2026-01-20T15:00",
  },
  {
    id: "rc9",
    projectId: "p1",
    taskType: "MTG",
    label: "その他",
    implScope: "その他",
    content: "チームリーダーtom1",
    isFavorite: true,
    isCompleted: false,
    duration: 30,
    xp: 20,
    createdAt: "2026-01-20T16:00",
  },
];

// 今日の始業で選択済みのRepoCa ID
export const todaySelectedIds: string[] = ["rc1", "rc2", "rc3", "rc4", "rc5"];

export const badges: Badge[] = [
  {
    id: "b1", name: "Next", description: "Next.jsを使用したPJに参加",
    icon: "▤", acquired: true, acquiredAt: "2026-01-15", tier: "gold",
    tierHistory: [
      { tier: "bronze", date: "2025-08-10", note: "ITS-xLPでNext.jsを初採用" },
      { tier: "silver", date: "2025-11-05", note: "Next.jsプロジェクト5件を完了" },
      { tier: "gold",   date: "2026-01-15", note: "Next.jsプロジェクト15件以上を経験" },
    ],
    nextTierCondition: "全ティア取得済み",
  },
  {
    id: "b2", name: "SCSS", description: "SCSSを使用したPJに参加",
    icon: "🤖", acquired: true, acquiredAt: "2026-02-01", tier: "silver",
    tierHistory: [
      { tier: "bronze", date: "2025-09-20", note: "コーポレートサイトリニューアルでSCSS導入" },
      { tier: "silver", date: "2026-02-01", note: "SCSSを使ったPJ10件に参加" },
    ],
    nextTierCondition: "SCSSプロジェクト20件に参加", nextTierProgress: 12, nextTierGoal: 20,
  },
  {
    id: "b3", name: "Java", description: "Javaを使用したPJに参加",
    icon: "〜", acquired: true, acquiredAt: "2026-02-10", tier: "bronze",
    tierHistory: [
      { tier: "bronze", date: "2026-02-10", note: "データ基盤構築PJでJavaバックエンドを担当" },
    ],
    nextTierCondition: "Javaプロジェクト5件に参加", nextTierProgress: 1, nextTierGoal: 5,
  },
  {
    id: "b4", name: "PHP", description: "PHPを使用したPJに参加",
    icon: "○", acquired: false,
    nextTierCondition: "PHPプロジェクトに1件参加", nextTierProgress: 0, nextTierGoal: 1,
  },
  {
    id: "b5", name: "WordPress", description: "WordPressを使用したPJに参加",
    icon: "△", acquired: false,
    nextTierCondition: "WordPressプロジェクトに1件参加", nextTierProgress: 0, nextTierGoal: 1,
  },
  {
    id: "b6", name: "AWS", description: "AWSを使用したPJに参加",
    icon: "☆", acquired: false,
    nextTierCondition: "AWSを使用したPJに1件参加", nextTierProgress: 0, nextTierGoal: 1,
  },
  {
    id: "b7", name: "TypeScript", description: "TypeScriptを活用",
    icon: "▤", acquired: true, acquiredAt: "2026-01-20", tier: "silver",
    tierHistory: [
      { tier: "bronze", date: "2025-10-01", note: "ITS-xLPフロント開発でTypeScriptを初導入" },
      { tier: "silver", date: "2026-01-20", note: "TypeScript採用PJ10件に参加" },
    ],
    nextTierCondition: "TypeScriptプロジェクト20件に参加", nextTierProgress: 15, nextTierGoal: 20,
  },
  {
    id: "b8", name: "React", description: "Reactを使用したPJに参加",
    icon: "🤖", acquired: true, acquiredAt: "2026-01-25", tier: "gold",
    tierHistory: [
      { tier: "bronze", date: "2025-07-15", note: "モバイルアプリ開発PJでReactを初採用" },
      { tier: "silver", date: "2025-10-20", note: "ReactプロジェクトをSPA化・5件完了" },
      { tier: "gold",   date: "2026-01-25", note: "Reactを主軸としたPJ15件以上に参加" },
    ],
    nextTierCondition: "全ティア取得済み",
  },
  {
    id: "b9", name: "Docker", description: "Dockerを使用したPJに参加",
    icon: "〜", acquired: false,
    nextTierCondition: "Dockerを使用したPJに1件参加", nextTierProgress: 0, nextTierGoal: 1,
  },
  {
    id: "b10", name: "PostgreSQL", description: "PostgreSQLを使用",
    icon: "○", acquired: false,
    nextTierCondition: "PostgreSQLを使用したPJに1件参加", nextTierProgress: 0, nextTierGoal: 1,
  },
  {
    id: "b11", name: "GraphQL", description: "GraphQLを使用したPJに参加",
    icon: "△", acquired: false,
    nextTierCondition: "GraphQLを使用したPJに1件参加", nextTierProgress: 0, nextTierGoal: 1,
  },
  {
    id: "b12", name: "Terraform", description: "Terraformを使用",
    icon: "☆", acquired: false,
    nextTierCondition: "Terraformを使用したPJに1件参加", nextTierProgress: 0, nextTierGoal: 1,
  },
];

export const missions: Mission[] = [
  {
    id: "m1",
    type: "daily",
    title: "今日のRepoCa",
    description: "本日3枚のRepoCaを作成する",
    reward: 30,
    passExpReward: 20,
    progress: 2,
    goal: 3,
    completed: false,
  },
  {
    id: "m2",
    type: "daily",
    title: "時間厳守",
    description: "定時までに終業報告を提出する",
    reward: 20,
    passExpReward: 15,
    progress: 0,
    goal: 1,
    completed: false,
  },
  {
    id: "m3",
    type: "monthly",
    title: "全力開発",
    description: "今月の開発タスクを20件完了する",
    reward: 200,
    passExpReward: 100,
    progress: 14,
    goal: 20,
    completed: false,
  },
  {
    id: "m4",
    type: "monthly",
    title: "皆勤チャレンジ",
    description: "今月全ての稼働日に報告を提出する",
    reward: 300,
    passExpReward: 150,
    progress: 18,
    goal: 20,
    completed: false,
  },
  {
    id: "m5",
    type: "unlimited",
    title: "外部案件挑戦",
    description: "外部案件に参加申請する",
    reward: 500,
    passExpReward: 200,
    progress: 0,
    goal: 1,
    completed: false,
  },
  {
    id: "m6",
    type: "daily",
    title: "シーズンデイリー",
    description: "本日の始業報告を提出する",
    reward: 0,
    passExpReward: 30,
    progress: 0,
    goal: 1,
    completed: false,
  },
  {
    id: "m7",
    type: "monthly",
    title: "シーズン貢献",
    description: "今月10回以上の報告を提出する",
    reward: 0,
    passExpReward: 250,
    progress: 7,
    goal: 10,
    completed: false,
  },
];

export const seasonPass: SeasonPass = {
  id: "sp1",
  seasonName: "スプリングシーズン 2026",
  endDate: "2026-04-01",
  passLevel: 7,
  passExp: 350,
  passExpToNext: 500,
  maxPassLevel: 50,
  rewards: [
    { level: 5,  type: "avatar_costume", name: "スプリングハット（仮）",        description: "シーズン限定アバター衣装", icon: "🎩", claimed: true },
    { level: 10, type: "physical",       name: "クオカード 500円（仮）",        description: "物理報酬",                 icon: "🎁", claimed: false },
    { level: 15, type: "avatar_costume", name: "サマーコスチューム（仮）",      description: "シーズン限定アバター衣装", icon: "👒", claimed: false },
    { level: 20, type: "physical",       name: "スペシャル賞品（仮）",          description: "最高報酬",                 icon: "🏆", claimed: false },
  ],
};
