import { User, Project, RepoCa, Badge, Mission } from "@/types";

export const currentUser: User = {
  id: "u1",
  name: "田中 太郎",
  teamId: "t1",
  level: 12,
  xp: 340,
  xpToNext: 500,
  currency: 1200,
  avatar: "warrior",
  isExternal: false,
};

export const projects: Project[] = [
  { id: "p1", name: "社内基盤システム刷新", teamId: "t1" },
  { id: "p2", name: "ECサイトリニューアル", teamId: "t1" },
  { id: "p3", name: "モバイルアプリ開発", teamId: "t2" },
  { id: "p4", name: "データ基盤構築", teamId: "t1" },
];

export const repoCas: RepoCa[] = [
  {
    id: "rc1",
    projectId: "p1",
    taskType: "開発",
    label: "新規作成",
    implScope: "フロント",
    content: "ログイン画面のUI実装",
    isFavorite: true,
    isCompleted: false,
    duration: 120,
    xp: 50,
    createdAt: "2026-02-24T09:00:00",
  },
  {
    id: "rc2",
    projectId: "p1",
    taskType: "開発",
    label: "修正",
    implScope: "バック",
    content: "認証APIのバグ修正",
    isFavorite: false,
    isCompleted: false,
    duration: 90,
    xp: 40,
    createdAt: "2026-02-24T10:30:00",
  },
  {
    id: "rc3",
    projectId: "p2",
    taskType: "MTG",
    label: "レビュー",
    implScope: "その他",
    content: "週次スプリントレビュー参加",
    isFavorite: false,
    isCompleted: true,
    duration: 60,
    xp: 20,
    createdAt: "2026-02-24T11:00:00",
  },
  {
    id: "rc4",
    projectId: "p3",
    taskType: "開発",
    label: "調査",
    implScope: "インフラ",
    content: "AWSコスト最適化調査",
    isFavorite: true,
    isCompleted: false,
    duration: 180,
    xp: 60,
    createdAt: "2026-02-24T13:00:00",
  },
];

export const badges: Badge[] = [
  {
    id: "b1",
    name: "初回報告",
    description: "初めて始業報告を提出した",
    icon: "🏅",
    acquired: true,
    acquiredAt: "2026-01-15",
  },
  {
    id: "b2",
    name: "皆勤賞",
    description: "1ヶ月間毎日報告を提出した",
    icon: "⭐",
    acquired: true,
    acquiredAt: "2026-02-01",
  },
  {
    id: "b3",
    name: "RepoCaマスター",
    description: "100枚のRepoCaを作成した",
    icon: "🃏",
    acquired: true,
    acquiredAt: "2026-02-10",
  },
  {
    id: "b4",
    name: "外部デビュー",
    description: "初めて外部案件に参加した",
    icon: "🌟",
    acquired: false,
  },
  {
    id: "b5",
    name: "フルスタッカー",
    description: "フロント・バック・インフラ全て経験",
    icon: "💎",
    acquired: false,
  },
  {
    id: "b6",
    name: "チームプレーヤー",
    description: "MTGに50回参加した",
    icon: "🤝",
    acquired: false,
  },
];

export const missions: Mission[] = [
  {
    id: "m1",
    type: "daily",
    title: "今日のRepoCa",
    description: "本日3枚のRepoCaを作成する",
    reward: 30,
    progress: 2,
    goal: 3,
    completed: false,
  },
  {
    id: "m2",
    type: "daily",
    title: "時間厳守",
    description: "定時までに終業報告を提出する",
    reward: 20,
    progress: 0,
    goal: 1,
    completed: false,
  },
  {
    id: "m3",
    type: "monthly",
    title: "全力開発",
    description: "今月の開発タスクを20件完了する",
    reward: 200,
    progress: 14,
    goal: 20,
    completed: false,
  },
  {
    id: "m4",
    type: "monthly",
    title: "皆勤チャレンジ",
    description: "今月全ての稼働日に報告を提出する",
    reward: 300,
    progress: 18,
    goal: 20,
    completed: false,
  },
  {
    id: "m5",
    type: "unlimited",
    title: "外部案件挑戦",
    description: "外部案件に参加申請する",
    reward: 500,
    progress: 0,
    goal: 1,
    completed: false,
  },
];
